from prompts.templates import (
    ROUTER_SYSTEM_PROMPT,
    SYNTHESIS_SYSTEM_PROMPT,
    SYNTHESIS_REVISION_PROMPT,
    QUALITY_EVAL_PROMPT,
)

__all__ = [
    "ROUTER_SYSTEM_PROMPT",
    "SYNTHESIS_SYSTEM_PROMPT",
    "SYNTHESIS_REVISION_PROMPT",
    "QUALITY_EVAL_PROMPT",
]
